### ISSUE TITLE
新版汉化载入模式后闪退求助！

### ISSUE THREAD

**Issue by wfntwl** [dounai2333/CSNS-Chinese-Localization#1]
汉化后能登录游戏，但是创建房间进入游戏预载资源后就闪退了，求助下！谢谢

**Comment by dounai2333** [comment]
如果你在汉化程序保持监控游戏文件读取时手动按下Delete键终止监控导致**国服的item.csv**被游戏加载就会导致此问题
但由于监控游戏文件时会导致严重的性能问题导致游戏加载时间变长（由1分钟左右变成至少10分钟），因此推荐在汉化程序的启动项中加入"-oldblockmethod"，此操作将会最低限禁止国服的item.csv的读取，同时避免游戏加载时间无限长，对于使用此启动项可能引发的问题请参考["为什么旧的文件阻止方式尚未完成"](https://github.com/dounai2333/CSNS-Chinese-Localization/blob/master/README_CN.md#为什么旧的文件阻止方式尚未完成)

对于item.csv被加载时导致问题的解释：
- 由于美服和国服的游戏特色不一样，因此如果你加载了国服的道具定义列表，但你的帐号里又存在一些国服并不存在的道具则会导致此问题。新创建的帐号则无此问题（避免获取到美服有而国服没有的道具即可）

如何鉴别item.csv已被游戏加载？
- 进入游戏后点击右上角数据，进入战场百科，检查武器里的超凡列表里是否存在"破军邪眼"和"光耀圣契"，如存在即为加载了国服的item.csv


如果在添加启动项后还有其他问题，请在下面跟进，我会做解答的

**Comment by wfntwl** [comment]
非常感谢这么耐心的解答，还真的是item的问题，国服比NZ多好多东西，我再去鼓捣鼓捣看看，谢谢！

**Comment by dounai2333** [comment]
如果你的闪退问题解决了那自然是再好不过，如果你遇到了新的问题或BUG，欢迎发起问题贴反馈！

**Comment by wfntwl** [comment]
好的谢谢！！问题已解决。
