### ISSUE TITLE
some doubts about the version of csn:s and cso cn client

### ISSUE THREAD

**Issue by buffrabbit** [dounai2333/CSNS-Chinese-Localization#3]
First thank you for providing the program!
The date I submitted this comment is 2021/4/23, and csn:s has updated the blazing nova,but cso cn has not. I copied the files from cso cn client and pasted them into the folders of csn:s, just as the readme did. However the game crashed after game logo showed up but the program seems to be working fine as it told:操作执行完毕，已经加载汉化！So is the difference between the two client versions causing this problem?

首先感谢大佬的汉化程序！
steam上的csn:s已经更新了新仲裁，国服的还没更新。我按照readme操作说明复制国服文件到csn:s端，然后加载N社反作弊时运行汉化程序，结果游戏弹个csn:s框之后闪退，试了好几次都不行。是不是国服和csn:s版本不一致导致的啊？

**Comment by dounai2333** [comment]
[CSO_Chinese_Localization.zip](https://github.com/dounai2333/CSNS-Chinese-Localization/files/6362735/CSO_Chinese_Localization.zip)
下这个 通过禁用了阻止2个文件的相关代码 可避免新版本闪退现象 请等待后续修复 在那之前请忍耐一些小问题
