### ISSUE TITLE
我有个问题啊

### ISSUE THREAD

**Issue by Xmug** [dounai2333/CSNS-Chinese-Localization#4]
你既然做的是汉化程序，那就是只给中国人用的了，为啥还要放个英文文档？

**Comment by dounai2333** [comment]
给感兴趣的非国人用于二次开发（例如在CSNS上读取韩语） 其次还会有用搜索功能好奇进来的老外 以英文作为默认README可以增加搜索曝光度
再额外的就是练练互译水平 我写README是先写英文再写中文 英文表达不完整的意思中文表达好了就再中译英 可以提高英语姿势

edit: 如果你去一个字一个字的扣我那个中文教程 你就会发现有些地方读起来不怎么顺 不像国人会写出来的玩意 毕竟我本来就是英译中 没怎么润色过 只有少部分中译英的部分才有明显感觉
